# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

resources:
  containers:
  - container: LinuxContainer
    image: ubuntu:14.04
  # - container: WindowsContainer
    # image: microsoft/nanoserver:2018

jobs:
# - job: LuxCoreRenderLinux
  # timeoutInMinutes: 0
  # pool:
    # vmImage: 'ubuntu-16.04'

  # container: LinuxContainer

  # steps:
  # - script: ./scripts/azurepipeline/build.sh
    # displayName: Building LuxCore
  # - script: ./scripts/azurepipeline/test.sh
    # displayName: Testing LuxCore
  # - task: PublishBuildArtifacts@1
    # inputs:
      # pathtoPublish: '$(System.DefaultWorkingDirectory)/LinuxCompile/target-64-sse2/luxcorerender-latest-linux64.tar.bz2'
      # artifactName: LuxCore
    # displayName: 'Upload luxcorerender-latest-linux64.tar.bz2'
    # condition: eq(variables['System.PullRequest.IsFork'], 'False')
- job: LuxCoreRenderWindows
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'

  # container: WindowsContainer

  steps:
  - script: ./scripts/azurepipeline/build.bat
    displayName: Getting deps and generating build files with CMake
  - task: MSBuild@1
    inputs:
      solution: '..\WindowsCompile\Build_CMake\LuxCore\LuxRays.sln' 
      # msbuildLocationMethod: 'version' # Optional. Options: version, location
      msbuildVersion: '15.0' # Optional. Options: latest, 15.0, 14.0, 12.0, 4.0
      msbuildArchitecture: 'x64' # Optional. Options: x86, x64
      # msbuildLocation: # Optional
      platform: 'x64' # Optional
      configuration: 'Release' # Optional
      msbuildArguments: '/nologo /verbosity:normal /p:WarningLevel=0' # Optional
      # clean: false # Optional
      maximumCpuCount: true # Optional
      # restoreNugetPackages: false # Optional
      # logProjectEvents: false # Optional
      createLogFile: true # Optional
    displayName: Building LuxCore
  - script: ./scripts/azurepipeline/post-build.bat
    displayName: Gathering and packing binaries
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)\..\WindowsCompile\luxcorerender-latest-win64.zip'
      artifactName: LuxCore
    displayName: 'Upload luxcorerender-latest-win64.zip'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')