# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

resources:
  containers:
  # - container: LinuxContainer
    # image: ubuntu:14.04
  - container: WindowsContainer
    image: windowsservercore:1803

jobs:
# - job: LuxCoreRenderLinux
  # timeoutInMinutes: 0
  # pool:
    # vmImage: 'ubuntu-16.04'

  # container: LinuxContainer

  # steps:
  # - script: ./scripts/azurepipeline/build.sh
    # displayName: Building LuxCore
  # - script: ./scripts/azurepipeline/test.sh
    # displayName: Testing LuxCore
  # - task: PublishBuildArtifacts@1
    # inputs:
      # pathtoPublish: '$(System.DefaultWorkingDirectory)/LinuxCompile/target-64-sse2/luxcorerender-latest-linux64.tar.bz2'
      # artifactName: LuxCore
    # displayName: 'Upload luxcorerender-latest-linux64.tar.bz2'
    # condition: eq(variables['System.PullRequest.IsFork'], 'False')
- job: LuxCoreRenderWindows
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'

  container: WindowsContainer

  steps:
  - script: echo hello from Windows
